on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: "Build on macos-latest"
    runs-on: macos-latest
    steps:
      - name: Initialize Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Initialize homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install dependencies
        run: |
          brew install protobuf
          brew install swift-protobuf
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Checkout foundation dependency
        uses: actions/checkout@v2
        with:
          repository: sandpolis/com.sandpolis.core.foundation
          path: module/com.sandpolis.core.foundation
      - name: Checkout instance dependency
        uses: actions/checkout@v2
        with:
          repository: sandpolis/com.sandpolis.core.instance
          path: module/com.sandpolis.core.instance
      - name: Checkout net dependency
        uses: actions/checkout@v2
        with:
          repository: sandpolis/com.sandpolis.core.net
          path: module/com.sandpolis.core.net
      - name: Checkout clientserver dependency
        uses: actions/checkout@v2
        with:
          repository: sandpolis/com.sandpolis.core.clientserver
          path: module/com.sandpolis.core.clientserver
      - name: Checkout desktop plugin
        uses: actions/checkout@v2
        with:
          repository: sandpolis/com.sandpolis.plugin.desktop
          path: plugin/com.sandpolis.plugin.desktop
      - name: Execute build
        run: |
          gradle --no-daemon :simulatorsList :build
